# fly.toml app configuration file generated for erasmoon on 2024-09-29T12:24:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'erasmoon'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[mounts]
  source="erasmoon_data"
  destination="/data"

[processes]
  app = "web: gunicorn app:app --workers=2 --threads=2"
