"""removed transport and groceries columns

Revision ID: 912606bcecb5
Revises: 828cb033bd40
Create Date: 2024-09-30 21:41:16.519454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '912606bcecb5'
down_revision: Union[str, None] = '828cb033bd40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_of_living', 'groceries_budget')
    op.drop_column('cost_of_living', 'transport_budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_of_living', sa.Column('transport_budget', sa.FLOAT(), nullable=True))
    op.add_column('cost_of_living', sa.Column('groceries_budget', sa.FLOAT(), nullable=True))
    # ### end Alembic commands ###
